
name: Create the json file listing all DD  

on:
  push:
    branches:
      - uni_proj_ld
  workflow_dispatch:

jobs:
  list-directories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: uni_proj_ld

    - name: List directories in TATA
      run: |
        directories=$(find * -type d | jq -R . | jq -s .)
        
        echo '{"@context": "000_context.jsonld", "datadescriptors": '"$directories"'}' > datadescriptors.json
        
    - name: Upload datadescriptors.json as artifact
      uses: actions/upload-artifact@v3
      with:
        name: datadescriptors.json
        path: ./datadescriptors.json

    - name: Commit datadescriptors.json
      run: |
        git add ./datadescriptors.json
        git commit -m "Generate datadescriptors.json listing all dd"
        git push origin uni_proj_ld 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
