
name: Create the json file listing all DD  

on:
  push:
    branches:
      - uni_proj_ld
  workflow_dispatch:

jobs:
  list-directories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: uni_proj_ld

    - name: List directories in TATA
      run: |
        directories=$(find * -type d | jq -R . | jq -s .)
        
        echo '{"@context": "000_context.jsonld", "datadescriptors": '"$directories"'}' > datadescriptors.json
        
    - name: Upload datadescriptors.json as artifact
      uses: actions/upload-artifact@v3
      with:
        name: datadescriptors.json
        path: ./datadescriptors.json

    - name: List json files in each datadescriptors and create JSON for each
      run: |
        # Loop through each directory in TATA
        for dir in *; do
          if [ -d "$dir" ]; then
            # Get the name of the directory
            dirname=$(basename "$dir")
            # List all JSON files inside the directory, strip path and .json extension
            json_files=$(find "$dir" -maxdepth 1 -type f -name "*.json" | sed 's|.*/||' | sed 's|.json||' | jq -R . | jq -s .)
            # Create the JSON file with the directory name in the root of the repository
        echo '{"@context":"000_context.jsonld", "terms": '"$json_files"'}' > "./${dirname}.json"
          fi
        done

    - name: Set up Git user for commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit datadescriptors.json
      run: |
        git add .
        git commit -m "Actions Generated files"
        git push origin uni_proj_ld 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
